### ISSUE TITLE
Ambiguous Timezone Rules

### ISSUE THREAD

**Issue by bcj** [quinnj/TimeZones.jl#16]
Right now, if two rules have overlapping transitions, `order_rules` will fail with the message `ERROR: Dates are probably not in order`. It seems like we might want to separate out out-of-order and overlapping rules to make things a bit clearer.

I need to look into the circumstances that can result in out-of-order for some test cases before I make a PR, but it seems like we should just have a secondary if within the failure case to differentiate and use an error along the lines of "ERROR: Ambiguous transition, two or more rules attempting to transition at {date}"

**Comment by omus** [comment]
The reason the error exists is to ensure that the transition dates are far enough apart such that we know we have sorted them correctly. Since transitions are typically ~6 months apart this never becomes a problem.

Can you give an example of zones/rules that are overlapping?

**Comment by bcj** [comment]
Oops, never replied to this. Having spent more time with `order_rules`, I think the current behavior is fine.

**Comment by omus** [comment]
Thanks
