### ISSUE TITLE
Ambiguous time zone error after using TimeZones.jl

### ISSUE THREAD

**Issue by slundberg** [quinnj/TimeZones.jl#19]
Based on the documentation I didn't expect this package to affect the way DateTime constructors work, but it seems to (Julia 0.4, latest master of TimeZones.jl):
```julia
julia> d = DateTime("2015-07-24T05:38:19.591Z", "yyyy-mm-ddTHH:MM:SS.sssZ")
2015-07-24T05:38:19.591

julia> using TimeZones

julia> d = DateTime("2015-07-24T05:38:19.591Z", "yyyy-mm-ddTHH:MM:SS.sssZ")
ERROR: ArgumentError: Ambiguious timezone
 in slotparse at /homes/gws/slund1/.julia/v0.4/TimeZones/src/timezones/io.jl:35
 in getslot at dates/io.jl:143
 in parse at dates/io.jl:158

julia>
```

I should note that I ran across this not by using `TimeZones` directly, but by using a library that used `TimeZones`. Perhaps I missed something that was intentional?

...a minor point but it might also be worth changing "Ambiguious" to "Ambiguous" at some point throughout  the code.

**Comment by omus** [comment]
The reason this is occurring is because both the `DateTime` and `ZonedDateTime` constructors make use of the same parsing system in Base.Dates. When TimeZones is loaded it adds support to the parsing system for handling the 'z' and 'Z' characters even though a `DateTime` can ignore it. I definitely think a change is in order since the parsing system could potentially be extended further and make 'T' a handled character which would horribly break things. I'll have to give this some thought on what needs to change to address this issue.

Thanks for the catch on the spelling mistake.

**Comment by slundberg** [comment]
Thanks for the clarification. I was just going through the source and saw that new "slots" were being registered by TimeZones, which makes sense. It seems like a solution (used by other libraries) would be to allow the specification of literals in a DateFormat such as `"2015-07-24\"T\"05:38:19.591\"Z\""`. It might also be best to fail for all non-literal characters reserved for future slots?

Perhaps this is already supported but, after looking at the code in Base, it does not look like it.

**Comment by omus** [comment]
A variant on your solution would be to escape characters in the format not intended to be consumed by slots. Something like `"yyyy-mm-dd\\THH:MM:SS.sss\\Z"`.

**Comment by slundberg** [comment]
I like that. Either way I assume those changes need to happen in Base, so feel free to close/leave this issue as you prefer.

**Comment by slundberg** [comment]
...and just to throw it out there, one other clean looking approach I have seen is:

`"2015-07-24'T'05:38:19.591'Z'"`

**Comment by omus** [comment]
Escaping the characters that you do not want to treat format characters is now supported: 
```julia
julia> d = DateTime("2015-07-24T05:38:19.591Z", "yyyy-mm-dd\\THH:MM:SS.sss\\Z")
2015-07-24T05:38:19.591

julia> using TimeZones

julia> d = DateTime("2015-07-24T05:38:19.591Z", "yyyy-mm-dd\\THH:MM:SS.sss\\Z")
2015-07-24T05:38:19.591
```
