### ISSUE TITLE
Feature Request: string -> ZonedDateTime

### ISSUE THREAD

**Issue by JonathanAnderson** [quinnj/TimeZones.jl#6]
I am looking to parse a string into a ZonedDateTime

For example I would like to parse `"2015-08-06T22:25:31+07:00"` into a `ZonedDateTime(DateTime(2015,08,06,22,25,31), FixedTimeZone("+07:00"))`

I think a reasonable method would be to define a new dateformat so that `ZonedDateTime("2015-08-06T22:25:31+07:00", some_dateformat)` would work but I am still working to understand how 'timezones/io.jl' is working.

Still, I figured I would put up my request for now since I think it would be useful.

**Comment by iamed2** [comment]
I think this is the format you're looking for:
```julia
ZonedDateTime("2015-08-06T22:25:31+07:00", "yyyy-mm-ddTHH:MM:SSzzzz")
```

These things should be documented though. Perhaps at some point we can get a function like Python's dateutil's parse, which makes a best-guess parsing.

**Comment by omus** [comment]
@iamed2 is correct. The `ZonedDateTime` parsing works using the same methods that `DateTime` provides. Eventually I'm planning on getting a more dynamic version of string parsing included. That may or may not be included in the TimeZones.jl package.

**Comment by JonathanAnderson** [comment]
Since this works I'll close the issue =)
